import type { Metadata } from 'next'
import { Handjet } from 'next/font/google'
import FlickeringGridLayout from './FlickeringGridLayout'
import './globals.css'

const handjet = Handjet({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={handjet.className}>
				<FlickeringGridLayout>{children}</FlickeringGridLayout>
			</body>
		</html>
	)
}
